### ISSUE TITLE
Error while running wisecondor

### ISSUE THREAD

**Issue by Kritikaraya** [rstraver/wisecondor#40]
I have 1 Female and 1 male samples which i got from illumina 1000 genome bam files. And 1 test samples to check for anueploidy.

All the files are located in 1folder
i tried running code alone for reference 
 `python wisecondor.py convert ../Human/Data/Female_0883.bam ../Human/Data/FeMale_trail.npz   binsize 250000`

and for test sepeartedly
python wisecondor.py convert ../Human/Data/Sample.bam ../Human/Data/sample.npz -binsize 50000

after i have done this 
I tried running 

`python wisecondor.py newref /home/molecular/Downloads/Human/Data/Ref/*.npz ./dataFiles/reference.npz -binsize 250000`

so for this i am getting error 
**Traceback (most recent call last):
  File "wisecondor.py", line 525, in <module>
    main()
  File "wisecondor.py", line 521, in main
    args.func(args)
  File "wisecondor.py", line 44, in toolNewref
    toolNewrefPrep(args)
  File "wisecondor.py", line 79, in toolNewrefPrep
    samples.append(scaleSample(npzdata['sample'].item(), npzdata['arguments'].item()['binsize'], args.binsize))
  File "/home/molecular/Downloads/wisecondor-master/wisetools.py", line 232, in scaleSample
    newLen = int(np.ceil(len(chromData)/float(scale)))
TypeError: object of type 'NoneType' has no len()**

I am new to this NIPT analysis. And i am not able to understand where i am going wrong.

If anyone the analysis pipeline please let me know

**Comment by rstraver** [comment]
Hi,
> I have 1 Female and 1 male samples

You'll have to provide more samples to train on, this won't work well if at all.

Also, what chromosome names do you use in your reference data?

**Comment by Kritikaraya** [comment]
**from .expected_mutual_info_fast import expected_mutual_information
/usr/local/lib/python2.7/dist-packages/sklearn/metrics/pairwise.py:30: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88**

This is warning i am getting

**Comment by rstraver** [comment]
Did you change anything and did the error go away in the meantime? What does the output look like now?

**Comment by Kritikaraya** [comment]
[sra_datat21.sorted_plot_z.pdf](https://github.com/VUmcCGP/wisecondor/files/2339535/sra_datat21.sorted_plot_z.pdf)
[sra_data_1_sorted_plot_z.pdf](https://github.com/VUmcCGP/wisecondor/files/2339537/sra_data_1_sorted_plot_z.pdf)


This is out put i got .
Is is correct ?
I am using reference as illumina sample and my test samples is Ion torrent both mapped with same reference genome and eliminated the error.

**Comment by rstraver** [comment]
It looks like the scripts ran but the results are far from useful. You should train WISECONDOR using several samples from the same machine and labflow as the test sample.

**Comment by ak-akku** [comment]
how can i get the npz file of the reference genome.... the input needed is a bam file and how can you create a bam file of  the reference genome

**Comment by rstraver** [comment]
You don't, samples are mapped to the reference genome and the mapped samples (bam files) are combined into a reference for WISECONDOR.
